configName: pic32cm_le00_curiosity_pro_freertos
folderName: ''
format_version: v1.0
frameworkPath: ../../../../../../../..
processor: PIC32CM5164LE00100
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;crypto;cryptoauthlib;csp;gfx;micrium_ucos3;net;touch;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-LE_DFP\1.0.53\atdf\PIC32CM5164LE00100.atdf
